#!/bin/bash

sway_folder="$HOME/.config/sway"
sway_config_file="$sway_folder/config"
sway_config_dir="$sway_folder/config.d"
sway_includes_file="$sway_config_dir/sway_configs.conf"

if [[ -f "$sway_includes_file" ]]; then
  [[ -f "$sway_config_file" ]] && rm "$sway_config_file"

  touch "$sway_config_file"

  echo "#### DO NOT EDIT THIS FILE, IT IS GENERATED." >> "$sway_config_file"
  echo "#### EDIT THE FILES HERE: $sway_folder/config.d/**/*" >> "$sway_config_file"

  include_file() {
    echo -ne "\n" >> "$sway_config_file"
    cat "$sway_config_dir/$1" >> "$sway_config_file"
  }

  get_file_name_from_line () {
    stripped_file_name=$(echo $* | sed 's/\(import \)\(.*.conf\)\(;\)/\2/')
    echo "$stripped_file_name"
  }

  exec 3< "$sway_includes_file"

  until [ "$done" ]
  do
    read <&3 config_line

    if [ $? != 0 ]; then
      done=1
      continue
    else
      if [[ "$config_line" == "import "* ]]; then
        file_name="$(get_file_name_from_line $config_line)"
        include_file "$file_name"
      fi
    fi
  done


else
  echo "ERROR:"
  echo "Please create the configs import file:"
  echo " $sway_config_dir/sway_configs.conf"
fi
