#!/usr/bin/env sh
vscodium \
    --install-extension aaron-bond.better-comments \
    --install-extension adpyke.vscode-sql-formatter \
    --install-extension alexcvzz.vscode-sqlite \
    --install-extension bradlc.vscode-tailwindcss \
    --install-extension dbaeumer.vscode-eslint \
    --install-extension editorconfig.editorconfig \
    --install-extension esbenp.prettier-vscode \
    --install-extension streetsidesoftware.code-spell-checker \
    --install-extension extr0py.vscode-relative-line-numbers \
    --install-extension foxundermoon.shell-format \
    --install-extension vscodevim.vim \
    --install-extension foxundermoon.shell-format \
    --install-extension yzane.markdown-pdf \
    --install-extension yzhang.markdown-all-in-one \
    --install-extension atishay-jain.all-autocomplete \
    --install-extension grapecity.gc-excelviewer \
    --install-extension jbockle.jbockle-format-files \
    --install-extension jebbs.plantuml \
    --install-extension mhutchie.git-graph \
    --install-extension mikestead.dotenv \
    --install-extension ms-azuretools.vscode-docker \
    --install-extension ms-kubernetes-tools.kind-vscode \
    --install-extension ms-kubernetes-tools.vscode-kubernetes-tools \
    --install-extension ms-python.python \
    --install-extension mtxr.sqltools \
    --install-extension redhat.vscode-xml \
    --install-extension redhat.vscode-yaml \
    --install-extension reditorsupport \
    --install-extension Tchoupinax.tilt \
    --install-extension unifiedjs.vscode-mdx \
    --install-extension vadistic.mdx-inline \
    --install-extension vscode-icons-team.vscode-icons \
    --install-extension xyc.vscode-mdx-preview
    --install-extension tomoki1207.pdf
    --install-extension phgn.vscode-starlark
