{
  options,
  config,
  pkgs,
  lib,
  host ? "",
  format ? "",
  inputs ? {},
  ...
}:
with lib;
with lib.plusultra; let
  cfg = config.caramelmint.services.blueman;
in {
  options.caramelmint.services.blueman = with types; {
    enable = mkBoolOpt false "Whether or not to enable and  configure blueman.";
  };

  config = mkIf cfg.enable {
    services.blueman.enable = true;
    # Should this hardware toggle be moved to each specific host's hardware.nix file? Sounds right, but the hardware.nix file supposedly should not be edited as it is generated by nixos-generate-config
    hardware.bluetooth.enable = true;
    caramelmint.home.extraOptions = {
      services.blueman-applet.enable = true;
    };
  };
}
